### ISSUE TITLE
GOES 15 map is off

### ISSUE THREAD

**Issue by kidshare** [pietern/goestools#31]
GOES 15 has moved to 128.57W and the map is off. I am receiving the GOES 15 images from GOES 17 relay. Everything else is working perfectly and I'm extremely pleased, thanks a bunch, I haven't had this much fun since I first tried wxtoimg several years ago!

![goes15_ir_20181211t180017z_fd](https://user-images.githubusercontent.com/11001506/49825424-3f31ed80-fd39-11e8-9a68-6b5ff89bbb19.jpg)

**Comment by pietern** [comment]
Thanks for reporting. I noticed this as well and hoped that the ground station HRIT feed assembly would be updated to fix this. With that not happening, the fix was easy. The override is in effect if the image was taken after Nov 7 and still includes a header with 135W as the longitude.

You can update to the latest version for the fix.

**Comment by pietern** [comment]
And great to hear you're having fun with it :+1:
