### ISSUE TITLE
Detect nanomsg drops

### ISSUE THREAD

**Issue by pietern** [pietern/goestools#8]
Right now nanomsg drops are silent. If packets are missing from the stream it is not possible to tell whether this is happening on the downlink or on the network. Detection for this should be added.

**Comment by pietern** [comment]
This is still a problem in theory but with the much larger buffer size it's not a problem in practice.

Ignoring and closing.

**Comment by eminence** [comment]
I think I might be running into this, due to a poor wifi link between goesrecv and goesproc.  My symptom is lots of "TP_PDU drop" in goesproc, but goesrecv is reporting a very constant number of received and a very lot number of dropped packets (so I don't think I'm running into #26).

So I'm interested in working on detecting this type of packet drops.  Do you have any suggestion about an approach to detect nanomsg packet drops?  Does nanomsg have some built-in functionality to handle this?  Or maybe the first few bytes of the packet could be used for a packet number counter?
